# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC


class Test123():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()

    def teardown_method(self, method):
        self.driver.quit()

    def test_123(self):
        wait = WebDriverWait(self.driver, 1)
        self.driver.get("http://10.0.0.22/")
        self.driver.set_window_size(1848, 1053)
        self.driver.find_element(By.ID, "login_login").click()
        self.driver.find_element(By.ID, "login_login").send_keys("admin")
        self.driver.find_element(By.ID, "login_password").send_keys("admin")
        self.driver.find_element(By.ID, "login_password").send_keys(Keys.ENTER)
        element = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".user-info")))
        self.driver.find_element(By.CSS_SELECTOR, ".user-info").click()
        element = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".ant-btn-primary > span")))
        self.driver.find_element(By.CSS_SELECTOR, ".ant-btn-primary > span").click()
