# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestLoginlogout():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_loginlogout(self):
        self.driver.get("http://10.0.0.74/")
        self.driver.set_window_size(1936, 1056)
        self.driver.find_element(By.NAME, "login").click()
        self.driver.find_element(By.NAME, "login").send_keys("admin")
        self.driver.find_element(By.NAME, "password").send_keys("admin")
        self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR,
                                           ".MuiButtonBase-root:nth-child(3) > .MuiIconButton-label path")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".MuiButtonBase-root:nth-child(3) > .MuiIconButton-label path").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, ".jss13 > .MuiButton-label")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".jss13 > .MuiButton-label").click()

